### ISSUE TITLE
我用模拟方式登陆一直报错

### ISSUE THREAD

**Issue by rmokerone** [liuzheng712/weibo#1]
这个是我用模拟方式获取到的req_login数据

``` html
    <html>
        <head>
        <title>����ͨ��֤</title>
        <meta http-equiv="refresh" content="0; url=&#39;http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack&retcode=4049&reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C2%EB&#39;"/>
        <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
        </head>
        <body bgcolor="#ffffff" text="#000000" link="#0000cc" vlink="#551a8b" alink="#ff0000">
        <script type="text/javascript" language="javascript">
        location.replace("http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack&retcode=4049&reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C2%EB");
        </script>
        </body>
        </html>
```

这个是报错内容
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    simuLogin()
  File "example.py", line 19, in simuLogin
    simu = Lweibo.simu()
  File "/home/masong/Coding/weibo/Lweibo.py", line 420, in **init**
    self.simu = weibo_login(username, pwd)
  File "/home/masong/Coding/weibo/Lweibo.py", line 163, in **init**
    self.login(username, pwd, cookie_file)
  File "/home/masong/Coding/weibo/Lweibo.py", line 221, in login
    return self.do_login(username, pwd, cookie_file)
  File "/home/masong/Coding/weibo/Lweibo.py", line 288, in do_login
    login_url = p.search(text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

比较奇怪的是，我昨天晚上登陆还一直很正常，今天打开就出错了。

**Comment by liuzheng** [comment]
@rmokerone 你这是账户被封的情况，换号重玩吧
